---
stages:
  - test
  - coverage

default:
  before_script:
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

.tests:
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb
  stage: test

test:2.4:
  extends: .tests
  image: 'ruby:2.4'

test:2.5:
  extends: .tests
  image: 'ruby:2.5'

test:2.6:
  extends: .tests
  image: 'ruby:2.6'

test:2.7:
  extends: .tests
  image: 'ruby:2.7'

test:jruby:
  extends: .tests
  image: 'jruby:9.2-jre'

coverage:
  image: 'ruby:2.7'
  script:
    - bundle exec rake test
  artifacts:
    paths:
      - coverage/
  stage: coverage
