---
default:
  before_script:
    - ruby -v
    - which ruby
    - gem install bundler --no-document
    - bundle install --jobs $(nproc)  "${FLAGS[@]}"

test:2.4:
  image: 'ruby:2.4'
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb

test:2.5:
  image: 'ruby:2.5'
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb

test:2.6:
  image: 'ruby:2.6'
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb

test:2.7:
  image: 'ruby:2.7'
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb
  artifacts:
    paths:
      - coverage/

test:jruby:
  image: 'jruby:9.2.12-jre'
  script:
    - bundle exec rake
    - cd test/integration && bundle install
    - bundle exec ruby api.rb
