---
dist: trusty
group: beta
sudo: false
language: ruby
cache: bundler
before_install:
  - gem install bundler -v '<2'
rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3
  - 2.6.0
  - rbx-3
  - jruby-9.1.16.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx-3
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
  - cd test/integration && bundle install
  - bundle exec ruby api.rb
