sudo: false
bundler_args: --jobs=3 --retry=3
language: ruby
cache: bundler
before_install:
  - gem update --remote bundler
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - ruby-head
  - jruby-19mode
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
notifications:
  email:
    on_success: change
    on_failure: always
script:
  - bundle exec rake
  - bundle exec rubocop
